
server:
  port: 28082

spring:
  application:
    name: order

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

  cloud:
    sentinel:
      eager: true
      enabled: true
      transport:
        dashboard: 127.0.0.1:8080 # Sentinel 控制台地址
      filter:
        url-patterns: /** # 拦截请求的地址。默认为 /*

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    registry-fetch-interval-seconds: 10 #从eureka服务器注册表中获取注册信息的时间间隔（s），默认为30秒
  instance:
    ip-address: localhost
    prefer-ip-address: true
